execution:
  - concurrency: 20
    ramp-up: 30s
    hold-for: 2m
    scenario: login-flow

scenarios:
  login-flow:
    script: ../jmx/login-test.jmx
    variables:
      BASE_URL: ${BASE_URL}
      USERNAME: test@example.com
      PASSWORD: testpassword

services:
  - module: passfail
    criteria:
      - avg-rt>1000ms for 10s, stop as failed
      - avg-rt>800ms for 5s, continue as failed
      - p90>2s for 10s, stop as failed
