included-configs:
  - login-test.yml
  - product-browse-test.yml
  - checkout-test.yml

settings:
  env:
    BASE_URL: ${BASE_URL}  # Will be passed from GitHub Actions
  aggregator: consolidator
  check-interval: 5s
  default-executor: jmeter

# modules:
#   blazemeter:
#     token: "7689408498ca26ff6301d0eb:c9219c32296d8e17dbfe9cbd06eddf56ff763d6ef08033581fe431f25f9bba6f89e82c0b"
#     test: "Google Test"  # Add a test name
#     project: "My Project"  # Add a project name

reporting:
  - module: final-stats
  - module: console
  - module: blazemeter
    project: NextJS App Testing
    test: Full E-commerce Flow
    report-name: E-Commerce User Flows
    auth:
      token: "7689408498ca26ff6301d0eb:c9219c32296d8e17dbfe9cbd06eddf56ff763d6ef08033581fe431f25f9bba6f89e82c0b"        # Set in environment variables

services:
  - module: monitoring
    local:
      - metrics:
          - cpu
          - memory
          - network
  - module: shellexec
    prepare:
      - "echo 'Preparing performance testing environment'"
    startup:
      - "echo 'Starting tests at: $(date)'"
    post-process:
      - "echo 'Tests completed at: $(date)'"
      - "mkdir -p artifacts/reports"
      - "cp *.jtl artifacts/reports/"
