name: Performance Testing

on:
  push:
    branches:
      - main
  deployment_status:
    environments:
      - production
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - login
          - product-browse
          - checkout

jobs:
  performance-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bzt
          pip install blazemeter-api-client

      # Set the Vercel URL from the deployment event or secrets
      - name: Set Vercel URL
        run: |
          if [ "${{ github.event_name }}" = "deployment_status" ]; then
            echo "VERCEL_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
          else
            echo "VERCEL_URL=${{ secrets.VERCEL_URL }}" >> $GITHUB_ENV
          fi
          echo "Using Vercel URL: ${{ env.VERCEL_URL }}"

      # Generate JMX files
      - name: Generate JMX Files
        run: |
          cd performance-tests/scripts
          chmod +x generate-jmx.sh
          ./generate-jmx.sh ${{ env.VERCEL_URL }}

      # Run different test types based on workflow dispatch input
      - name: Run Full Test Suite (Default)
        if: github.event.inputs.test_type == 'full' || github.event.inputs.test_type == '' || github.event_name == 'deployment_status' || github.event_name == 'push'
        env:
          BZ_TOKEN: ${{ secrets.BZ_TOKEN }}
          BASE_URL: ${{ env.VERCEL_URL }}
        run: |
          bzt performance-tests/config/master-config.yml -o settings.env.BASE_URL=$BASE_URL -report

      - name: Run Login Test Only
        if: github.event.inputs.test_type == 'login'
        env:
          BZ_TOKEN: ${{ secrets.BZ_TOKEN }}
          BASE_URL: ${{ env.VERCEL_URL }}
        run: |
          bzt performance-tests/config/login-test.yml -o settings.env.BASE_URL=$BASE_URL -report

      # - name: Save test artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: performance-reports
      #     path: |
      #       performance-tests/jmx/
      #       performance-tests/artifacts/
      #       .logs/
      #       *.jtl
